# Generated by Django 3.1.2 on 2020-10-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shopping_lists.fridge')),
            ],
            options={
                'unique_together': {('name', 'fridge')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shopping_lists.fridge')),
            ],
            options={
                'unique_together': {('name', 'fridge')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avg_time_between_purchases', models.IntegerField(default=None, null=True)),
                ('last_bought', models.DateTimeField(default=None, null=True)),
                ('is_in_fridge', models.BooleanField()),
                ('is_in_shopping_list', models.BooleanField()),
                ('unit', models.CharField(default='', max_length=16)),
                ('quantity', models.FloatField(default=None, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_lists.category')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_lists.fridge')),
                ('shops', models.ManyToManyField(related_name='products', to='shopping_lists.Shop')),
            ],
            options={
                'unique_together': {('name', 'fridge')},
            },
        ),
    ]
