# Generated by Django 3.1.2 on 2020-10-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='shopping_lists.fridge')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avg_time_between_purchases', models.IntegerField(default=None, null=True)),
                ('last_bought', models.DateTimeField(default=None, null=True)),
                ('is_in_fridge', models.BooleanField()),
                ('is_in_shopping_list', models.BooleanField()),
                ('unit', models.CharField(default='', max_length=16)),
                ('quantity', models.FloatField(default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_lists.category')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_lists.shoppinglist')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_lists.space')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridges', to='shopping_lists.space'),
        ),
    ]
