# Generated by Django 3.1.2 on 2020-10-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fridge',
            unique_together={('name', 'space')},
        ),
    ]
