# Generated by Django 3.1.2 on 2020-10-17 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='users',
            field=models.ManyToManyField(related_name='fridges', to=settings.AUTH_USER_MODEL),
        ),
    ]
