# Generated by Django 3.1.2 on 2020-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0003_auto_20201018_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_in_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_shopping_list',
            field=models.BooleanField(default=True),
        ),
    ]
