# Generated by Django 3.1.2 on 2020-10-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0003_auto_20201014_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shopping_lists.space'),
            preserve_default=False,
        ),
    ]
