# Generated by Django 3.1.2 on 2020-10-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0004_auto_20201018_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_fridge',
        ),
    ]
