# Generated by Django 3.1.2 on 2020-10-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_lists', '0005_remove_product_is_in_fridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_recipe', models.FloatField(default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='shopping_lists.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('times_used', models.IntegerField(default=0)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='shopping_lists.fridge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(through='shopping_lists.ProductInRecipe', to='shopping_lists.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_lists.recipe'),
        ),
    ]
