# Generated by Django 3.1.2 on 2020-10-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0006_auto_20201019_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'fridge')},
        ),
    ]
