# Generated by Django 3.1.2 on 2020-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0009_remove_invitation_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.IntegerField(choices=[(0, 'shopping list'), (1, 'fridge'), (2, 'in storage')], default=2),
        ),
    ]
