# Generated by Django 3.1.2 on 2020-10-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0011_auto_20201031_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_shopping_list',
        ),
    ]
