# Generated by Django 3.1.2 on 2020-10-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0012_remove_product_is_in_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.IntegerField(choices=[(0, 'Lista zakupów'), (1, 'Lodówka'), (2, 'Przechowalnia')], default=2),
        ),
    ]
